coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 1%     # Autorise une baisse jusqu’à 74%
        informational: false
    patch:
      default:
        target: 75%
        threshold: 1%
        informational: false
comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
