version: '3.8'

services:
  php:
    build: .
    ports:
      - "8020:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - memcached

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8040:80"

  memcached:
    image: memcached:alpine
    expose:
      - "11211"
